title: Zirui Li
description: hello
# 使用 minimal mistakes 主题
remote_theme: mmistakes/minimal-mistakes

# 开启侧边栏
minimal_mistakes_skin: default

author: 
  avatar: /assets/bio_photo/avatar.jpg
  email: lzrqna974@gmail.com
  bio: none

defaults: 
  - scope: 
      path: ""
      type: "pages"
    values: 
      layout: single
      sidebar:
        nav: "sidebar"
